// Generated by view binder compiler. Do not edit!
package com.example.musicplayer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.musicplayer.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentPlayingBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView albumCover;

  @NonNull
  public final ImageButton playButton;

  @NonNull
  public final ImageButton shuffle;

  @NonNull
  public final ImageButton skipBackward;

  @NonNull
  public final ImageButton skipForward;

  @NonNull
  public final TextView songAlbum;

  @NonNull
  public final SeekBar songSeekBar;

  @NonNull
  public final TextView songTitle;

  @NonNull
  public final ImageButton trackRepeat;

  private FragmentPlayingBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView albumCover,
      @NonNull ImageButton playButton, @NonNull ImageButton shuffle,
      @NonNull ImageButton skipBackward, @NonNull ImageButton skipForward,
      @NonNull TextView songAlbum, @NonNull SeekBar songSeekBar, @NonNull TextView songTitle,
      @NonNull ImageButton trackRepeat) {
    this.rootView = rootView;
    this.albumCover = albumCover;
    this.playButton = playButton;
    this.shuffle = shuffle;
    this.skipBackward = skipBackward;
    this.skipForward = skipForward;
    this.songAlbum = songAlbum;
    this.songSeekBar = songSeekBar;
    this.songTitle = songTitle;
    this.trackRepeat = trackRepeat;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentPlayingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentPlayingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_playing, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentPlayingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.album_cover;
      ImageView albumCover = ViewBindings.findChildViewById(rootView, id);
      if (albumCover == null) {
        break missingId;
      }

      id = R.id.play_button;
      ImageButton playButton = ViewBindings.findChildViewById(rootView, id);
      if (playButton == null) {
        break missingId;
      }

      id = R.id.shuffle;
      ImageButton shuffle = ViewBindings.findChildViewById(rootView, id);
      if (shuffle == null) {
        break missingId;
      }

      id = R.id.skip_backward;
      ImageButton skipBackward = ViewBindings.findChildViewById(rootView, id);
      if (skipBackward == null) {
        break missingId;
      }

      id = R.id.skip_forward;
      ImageButton skipForward = ViewBindings.findChildViewById(rootView, id);
      if (skipForward == null) {
        break missingId;
      }

      id = R.id.song_album;
      TextView songAlbum = ViewBindings.findChildViewById(rootView, id);
      if (songAlbum == null) {
        break missingId;
      }

      id = R.id.song_seek_bar;
      SeekBar songSeekBar = ViewBindings.findChildViewById(rootView, id);
      if (songSeekBar == null) {
        break missingId;
      }

      id = R.id.song_title;
      TextView songTitle = ViewBindings.findChildViewById(rootView, id);
      if (songTitle == null) {
        break missingId;
      }

      id = R.id.track_repeat;
      ImageButton trackRepeat = ViewBindings.findChildViewById(rootView, id);
      if (trackRepeat == null) {
        break missingId;
      }

      return new FragmentPlayingBinding((ConstraintLayout) rootView, albumCover, playButton,
          shuffle, skipBackward, skipForward, songAlbum, songSeekBar, songTitle, trackRepeat);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
