// Generated by view binder compiler. Do not edit!
package com.example.musicplayer.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.musicplayer.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SongItemBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final MaterialCardView albumCard;

  @NonNull
  public final ImageView albumThumbnail;

  @NonNull
  public final TextView songListArtist;

  @NonNull
  public final TextView songListTitle;

  private SongItemBinding(@NonNull ConstraintLayout rootView, @NonNull MaterialCardView albumCard,
      @NonNull ImageView albumThumbnail, @NonNull TextView songListArtist,
      @NonNull TextView songListTitle) {
    this.rootView = rootView;
    this.albumCard = albumCard;
    this.albumThumbnail = albumThumbnail;
    this.songListArtist = songListArtist;
    this.songListTitle = songListTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SongItemBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SongItemBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.song_item, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SongItemBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.album_card;
      MaterialCardView albumCard = ViewBindings.findChildViewById(rootView, id);
      if (albumCard == null) {
        break missingId;
      }

      id = R.id.album_thumbnail;
      ImageView albumThumbnail = ViewBindings.findChildViewById(rootView, id);
      if (albumThumbnail == null) {
        break missingId;
      }

      id = R.id.song_list_artist;
      TextView songListArtist = ViewBindings.findChildViewById(rootView, id);
      if (songListArtist == null) {
        break missingId;
      }

      id = R.id.song_list_title;
      TextView songListTitle = ViewBindings.findChildViewById(rootView, id);
      if (songListTitle == null) {
        break missingId;
      }

      return new SongItemBinding((ConstraintLayout) rootView, albumCard, albumThumbnail,
          songListArtist, songListTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
